packaging_format = 2

id = "myddlware"
name = "Myddleware"

version = "4.3.0~ynh1"

[upstream]
version = "4.3.0"
license = "AGPL-3.0-or-later"
website = "https://www.myddleware.com/"
admindoc = "https://github.com/Myddleware/myddleware/wiki"
userdoc = "https://github.com/Myddleware/myddleware/wiki"
code = "https://github.com/Myddleware/myddleware"

maintainers = ["verzog"]

[description]
en = "Open-source middleware to connect and sync data across business applications"
fr = "Middleware libre pour connecter et synchroniser des données entre applications"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "armhf", "arm64"]
multi_instance = true
ldap = "not_relevant"
sso = false
disk = "1200M"
ram.build = "256M"
ram.runtime = "512M"

[install]

  [install.domain]
  type = "domain"

  [install.path]
  type = "path"
  default = "/myddlware"

  [install.init_main_permission]
  type = "group"
  default = "visitors"

  [install.admin]
  ask.en = "Administrator email for Myddleware"
  type = "string"

[resources]

  [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Myddleware/myddleware/archive/refs/tags/v4.3.0.zip"
    sha256 = "4afd593c32b4b706082450c6e7120d8e3cbb2346e907b738ebea743173b715ea"

  [resources.system_user]

  [resources.install_dir]
  path = "/var/www/myddlware"

  [resources.permissions]
    [resources.permissions.main]
    url = "/"
