#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

domain=$(ynh_app_setting_get --app="$app" --key=domain)
install_dir=$(ynh_app_setting_get --app="$app" --key=install_dir)
phpversion=$(ynh_app_setting_get --app="$app" --key=phpversion)

#=================================================
# BACKUP FILES
#=================================================

ynh_script_progression "Backing up application files..."
ynh_backup --src_path="$install_dir"

nginx_conf_path=/etc/nginx/conf.d/$domain.d/$app.conf
if [ -f "$nginx_conf_path" ]; then
    ynh_backup --src_path="$nginx_conf_path"
fi

fpm_conf_path=/etc/php/$phpversion/fpm/pool.d/$app.conf
if [ -f "$fpm_conf_path" ]; then
    ynh_backup --src_path="$fpm_conf_path"
fi

ynh_script_progression "Backup completed"
