#!/bin/bash
set -eu

source /usr/share/yunohost/helpers

ynh_abort_if_errors

app=$YNH_APP_INSTANCE_NAME
final_path=$(ynh_app_setting_get --app="$app" --key=final_path)
domain=$(ynh_app_setting_get --app="$app" --key=domain)
phpversion=$(ynh_app_setting_get --app="$app" --key=phpversion)
db_name=$(ynh_app_setting_get --app="$app" --key=db_name)
db_user=$(ynh_app_setting_get --app="$app" --key=db_user)
db_pwd=$(ynh_app_setting_get --app="$app" --key=db_pwd)

ynh_script_progression --message="Backing up Myddleware files" --time --weight=1
ynh_backup --src_path="$final_path"
ynh_backup --src_path="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_backup --src_path="/etc/php/$phpversion/fpm/pool.d/$app.conf"

ynh_script_progression --message="Dumping database" --time --weight=1
ynh_mysql_dump_db --db_name="$db_name" --db_user="$db_user" --db_pwd="$db_pwd" > "$YNH_BACKUP_DIR/db.sql"

ynh_script_success
