#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

domain=$(ynh_app_setting_get --app="$app" --key=domain)
path_url=$(ynh_app_setting_get --app="$app" --key=path)
phpversion=$(ynh_app_setting_get --app="$app" --key=phpversion)
install_dir=$(ynh_app_setting_get --app="$app" --key=install_dir)

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================

ynh_script_progression "Updating NGINX configuration..."
nginx_conf_path=/etc/nginx/conf.d/$domain.d/$app.conf
ynh_replace_string --match_string="__DOMAIN__" --replace_string="$new_domain" --target_file=conf/nginx.conf | \
    ynh_replace_string --match_string="__PATH__" --replace_string="$new_path" | \
    ynh_replace_string --match_string="__FINALPATH__" --replace_string="$install_dir" | \
    ynh_replace_string --match_string="__PHP_VERSION__" --replace_string="$phpversion" | \
    ynh_replace_string --match_string="__APP__" --replace_string="$app" > "$nginx_conf_path"

#=================================================
# SAVE NEW SETTINGS
#=================================================

ynh_app_setting_set --app="$app" --key=domain --value="$new_domain"
ynh_app_setting_set --app="$app" --key=path --value="$new_path"

#=================================================
# RELOAD SERVICES
#=================================================

ynh_script_progression "Reloading services..."
ynh_systemd_action --service="php$phpversion-fpm" --action=reload
ynh_systemd_action --service=nginx --action=reload

ynh_script_progression "URL change completed"
