#!/bin/bash
set -eu

source /usr/share/yunohost/helpers
source "$(dirname "$0")/_common.sh"

ynh_script_progression --message="Removing NGINX configuration"
ynh_remove_nginx_config

ynh_script_progression --message="Removing PHP-FPM pool"
ynh_remove_fpm_config
