#!/bin/bash
set -eu

source /usr/share/yunohost/helpers

ynh_abort_if_errors

app=$YNH_APP_INSTANCE_NAME
final_path=$(ynh_app_setting_get --app="$app" --key=final_path)
domain=$(ynh_app_setting_get --app="$app" --key=domain)
phpversion=$(ynh_app_setting_get --app="$app" --key=phpversion)
db_name=$(ynh_app_setting_get --app="$app" --key=db_name)
db_user=$(ynh_app_setting_get --app="$app" --key=db_user)
db_pwd=$(ynh_app_setting_get --app="$app" --key=db_pwd)

ynh_script_progression --message="Recreating system user" --time --weight=1
ynh_system_user_create --username="$app"

ynh_script_progression --message="Restoring files" --time --weight=1
ynh_restore_file --origin_path="$final_path"
ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_restore_file --origin_path="/etc/php/$phpversion/fpm/pool.d/$app.conf"
chown -R "$app:$app" "$final_path"

ynh_script_progression --message="Restoring database" --time --weight=1
ynh_mysql_db_create --db_user="$db_user" --db_name="$db_name" --db_pwd="$db_pwd"
ynh_mysql_execute_file --database="$db_name" --user="$db_user" --password="$db_pwd" --file="$YNH_BACKUP_DIR/db.sql"

ynh_script_progression --message="Reloading services" --time --weight=1
ynh_systemd_action --service_name="php${phpversion}-fpm" --action="reload" --log_path="/var/log/php${phpversion}-fpm/$app.log" || true
ynh_systemd_action --service_name="nginx" --action="reload" || true

ynh_script_success
