#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

domain=$(ynh_app_setting_get --app="$app" --key=domain)
path_url=$(ynh_app_setting_get --app="$app" --key=path)
install_dir=$(ynh_app_setting_get --app="$app" --key=install_dir)
phpversion=$(ynh_app_setting_get --app="$app" --key=phpversion)

#=================================================
# RESTORE FILES
#=================================================

ynh_script_progression "Restoring application files..."
ynh_restore --src_path="$install_dir"

nginx_conf_path=/etc/nginx/conf.d/$domain.d/$app.conf
ynh_restore --src_path="$nginx_conf_path"

fpm_conf_path=/etc/php/$phpversion/fpm/pool.d/$app.conf
ynh_restore --src_path="$fpm_conf_path"

#=================================================
# RELOAD SERVICES
#=================================================

ynh_script_progression "Reloading services..."
ynh_systemd_action --service="php$phpversion-fpm" --action=reload
ynh_systemd_action --service=nginx --action=reload

ynh_script_progression "Restore completed"
