#!/bin/bash
set -eu

source /usr/share/yunohost/helpers
source "$(dirname "$0")/_common.sh"

ynh_script_progression --message="Restoring files"
ynh_restore_file --origin_path="$install_dir"
ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_restore_file --origin_path="/etc/php/$phpversion/fpm/pool.d/$app.conf"
chown -R "$app:$app" "$install_dir"

ynh_script_progression --message="Restoring database"
ynh_mysql_connect_as --user="$db_user" --password="$db_pwd" --database="$db_name" < ./db.sql

ynh_script_progression --message="Reloading services"
ynh_systemd_action --service_name="php${phpversion}-fpm" --action=reload
ynh_systemd_action --service_name=nginx --action=reload
